apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: ${PROJECT_NAME}
spec:
  source:
    type: Binary
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: DockerImage
        name: "registry.access.redhat.com/ubi8/openjdk-17:latest"
      env:
        - name: MAVEN_ARGS
          value: "-Popenshift -DskipTests"
  output:
    to:
      kind: ImageStreamTag
      name: "${PROJECT_NAME}:latest"

